### ISSUE TITLE
Make taskbar button dark on light theme

### ISSUE THREAD

**Issue by Pupcheg** [TheKing-OfTime/YandexMusicModClient#12]
When Windows has a light theme, make the taskbar buttons dark

Now:
![{AED13053-D5EC-41D2-9318-6B40A0FFC34F}](https://github.com/user-attachments/assets/8c2d469e-11f4-4508-9aab-82c27084fa98)

Example:
![{E6F9660A-7D24-4BFF-8C6F-4A63A1566474}](https://github.com/user-attachments/assets/472f26be-32ff-4170-b1e2-dd4ebd14ce52)

**Comment by TheKing-OfTime** [comment]
Added in 1.15.6
