### ISSUE TITLE
Изменение "Горячих клавиш".

### ISSUE THREAD

**Issue by sifocks** [TheKing-OfTime/YandexMusicModClient#14]
Привет! 

В Spotify можно было пользоваться горячими клавишами с помощью windows(win+F1-9), для работы с плеером внутри других приложений(Например игры). Однако в Яндекс.Музыке клавиши фиксированные и невозможно даже изменить, приложением по умолчанию тоже не установить. Есть возможность добавить изменение горячих клавиш, что бы была возможность менять треки не сворачивая приложения? Желательно так же сочетание клавиш (win+F1-9)

![image](https://github.com/user-attachments/assets/7b547099-8858-4b42-9ce6-67abe974cd0a)

**Comment by TheKing-OfTime** [comment]
Вы можете назначить горячие клавиши в `%appdata%/YandexMusic/config.json`
Это упоминается в readme https://github.com/TheKing-OfTime/YandexMusicModClient/blob/master/doc/ru/README.md#глобальные-хоткеи

К тому же хоткеи прописанные там срабатывают даже когда приложение свёрнуто.
