### ISSUE TITLE
Возможность отключить интеграцию с media keys.

### ISSUE THREAD

**Issue by xzyxzy** [TheKing-OfTime/YandexMusicModClient#16]
Здравствуйте, очень бы хотелось иметь возможность отключить показ трека стандартным оповещением windows.
А-ля отключение "Hardware Media Key Handling" в хроме. Спасибо за мод!

![image](https://github.com/user-attachments/assets/05ed2237-8afc-4a3f-b4fa-5e79e6180276)

**Comment by TheKing-OfTime** [comment]
Здравствуйте. Попробуйте в свойствах ярлыка запуска Яндекс музыки добавить `--disable-features=HardwareMediaKeyHandling`

**Comment by xzyxzy** [comment]
Ой спасибо, помогло. Я думал такой параметр только для дискорда прокатывает. :)
