### ISSUE TITLE
баг с горячей клавишей ctrl + s

### ISSUE THREAD

**Issue by iAnvar** [TheKing-OfTime/YandexMusicModClient#20]
Когда у меня запущено приложения яндекс музыка, в ОС перестает работать хоткей ctrl + s. Когда закрываю приложения все нормально. Пока что заметил проблему только с этим хоткеем.

**Comment by TheKing-OfTime** [comment]
Мне нужны настойки модификации. Их можно найти по пути `%appdata%/YandexMusic/config.json`. В них помимо прочего должен находиться список глобальных горячих клавиш. Возможно проблема в том что приложение резервирует это сочетание клавиш под себя

**Comment by iAnvar** [comment]
`{
	"hasRecentlyLaunched": true,
	"version": "5.28.4",
	"deviceId": "f9a38fbacd06d6e74974afc19ba6320d2fe01f3973a7d013617e5ca83de90e59",
	"uuid": "50d4aaf1-157b-40e1-9e32-88e93a063c26",
	"deviceSoftwareRevision": "d46f7d335ad9c7c28a94ef79afa4f1a2",
	"deviceCpuRevision": "57299a944c5db1499af968483d3ccb56",
	"tracksAvailabilityUpdatedAt": 1731905400154,
	"repositoryMetaUpdatedAt": 1731879000514,
	"windowDimensions": {
		"width": 1280,
		"height": 800
	},
	"modFeatures": {
		"discordRPC": {
			"enable": true,
			"applicationIDForRPC": "1124055337234858005",
			"showButtons": true,
			"showSmallIcon": false,
			"showAlbum": true,
			"overrideDeepLinksExperiment": false,
			"showGitHubButton": true,
			"afkTimeout": 15
		},
		"taskBarExtensions": {
			"enable": true
		},
		"vibeAnimationEnhancement": {
			"maxFPS": 25,
			"intensityCoefficient": 1,
			"linearDeBoost": 2,
			"playOnAnyEntity": false,
			"disableRendering": false
		},
		"playerBarEnhancement": {
			"showDislikeButton": true,
			"showCodecInsteadOfQualityMark": false
		},
		"globalShortcuts": {
			"TOGGLE_PLAY": "Ctrl+K",
			"MOVE_FORWARD": "Ctrl+L",
			"MOVE_BACKWARD": "Ctrl+J",
			"TOGGLE_SHUFFLE": "Ctrl+S"
		}
	},
	"enableDevTools": false,
	"enableAutoUpdates": false
}`

**Comment by iAnvar** [comment]
{
	"hasRecentlyLaunched": true,
	"version": "5.28.4",
	"deviceId": "f9a38fbacd06d6e74974afc19ba6320d2fe01f3973a7d013617e5ca83de90e59",
	"uuid": "50d4aaf1-157b-40e1-9e32-88e93a063c26",
	"deviceSoftwareRevision": "d46f7d335ad9c7c28a94ef79afa4f1a2",
	"deviceCpuRevision": "57299a944c5db1499af968483d3ccb56",
	"tracksAvailabilityUpdatedAt": 1731905400154,
	"repositoryMetaUpdatedAt": 1731879000514,
	"windowDimensions": {
		"width": 1280,
		"height": 800
	},
	"modFeatures": {
		"discordRPC": {
			"enable": true,
			"applicationIDForRPC": "1124055337234858005",
			"showButtons": true,
			"showSmallIcon": false,
			"showAlbum": true,
			"overrideDeepLinksExperiment": false,
			"showGitHubButton": true,
			"afkTimeout": 15
		},
		"taskBarExtensions": {
			"enable": true
		},
		"vibeAnimationEnhancement": {
			"maxFPS": 25,
			"intensityCoefficient": 1,
			"linearDeBoost": 2,
			"playOnAnyEntity": false,
			"disableRendering": false
		},
		"playerBarEnhancement": {
			"showDislikeButton": true,
			"showCodecInsteadOfQualityMark": false
		},
		"globalShortcuts": {
			"TOGGLE_PLAY": "Ctrl+K",
			"MOVE_FORWARD": "Ctrl+L",
			"MOVE_BACKWARD": "Ctrl+J",
			"TOGGLE_SHUFFLE": "Ctrl+S"
		}
	},
	"enableDevTools": false,
	"enableAutoUpdates": false
}

**Comment by TheKing-OfTime** [comment]
Переназначьте или удалите эту строчку. Проблема должна пропасть
![image](https://github.com/user-attachments/assets/43c3d7e9-4b51-48a8-a90f-f1007f3e605f)

**Comment by iAnvar** [comment]
да так и было, спасибо исправил!
