### ISSUE TITLE
Перехват действий с винды?

### ISSUE THREAD

**Issue by Farruh4eg** [TheKing-OfTime/YandexMusicModClient#23]
**Describe the bug**
Клиент вроде как перехватывает действия с винды. Столкнулся с этим когда хотел открыть загрузки в браузере, прожал CTRL+J и по итогу у меня просто включался предыдущий трек в ЯМе (при этом браузер никак не отреагировал). Сам клиент ЯМы при этом был свёрнут. Может это баг самого клиента, а не мода

**To Reproduce**
1. Свернуть клиент Яндекс.Музыка
2. Прожать CTRL+J
3. У нас включился предыдущий трек

**Expected behavior**
Клиент яндекс музыки будучи свёрнутым не должен реагировать на нажатия клавиш

**Screenshots/Video**
Нет

**Client info (please complete the following information):**
 - OS: Windows 10
 - Modification version 1.17.3
 - Yandex Music version 5.29.3

**Additional context**
Нет

**Comment by TheKing-OfTime** [comment]
Это не баг. Это функция глобальных горячих клавиш о которой заявлено в README.me. Настроить их можно в файле `%appdata%/YandexMusic/config.json`
Чтобы отключить отчистите список горячих клавиш.
Либо вы можете поменять назначение клавиш на более удобное для вас

**Comment by romanmatv** [comment]
Зато работает как баг. Я несколько дней гадал, почему стандартная комбинация Ctrl+S не работает вообще везде, пока не увидел этот тред.
Обнуляется событие нажатия клавиши, но остается событие отжатия. В результате ни один текстовый редактор не может поймать стандартное сочетания клавиш сохранения документа.
Понимаю, что это глобальные хоткеи, которые по идее должны работать не зависимо от фокуса на программу, но весьма сомнительно вешать на них популярные сочетания с совершенно другим смыслом и блокировать их использование в других программах.

**Comment by TheKing-OfTime** [comment]
Я согласен что я выбрал неудачное сочетание клавиш для хоткеев по умолчанию. Исправлю это в будущем
