### ISSUE TITLE
curl: (3) URL rejected: Bad hostname

### ISSUE THREAD

**Issue by mak7im01** [TheKing-OfTime/YandexMusicModClient#27]
Здравствуйте. Во время установки 5.32.2 версии появляется данная ошибка
![Скриншот](https://github.com/user-attachments/assets/262c7c99-f3b3-4d22-88f5-e2ba31241e52)

**Comment by TheKing-OfTime** [comment]
Проверьте настройки DNS. Я рекомендую 1.1.1.1 и 8.8.8.8.
Если это не поможет попробуйте в ручную скачать файл по ссылке https://github.com/TheKing-OfTime/YandexMusicModClient/releases/latest/download/app.asar
Затем вам нужно вставить с заменой этот файл по пути %localappdata%/Programs/YandexMusic/resources/app.asar

**Comment by mak7im01** [comment]
Спасибо
