### ISSUE TITLE
Incorrect display of uploaded tracks

### ISSUE THREAD

**Issue by Shockwave211112** [TheKing-OfTime/YandexMusicModClient#3]
If a track that is manually uploaded to Yandex is turned on, then the discord shows the track that was played before and playback time is wrong.

**Repetition**
1. Add "your" track to the queue with the next track
2. Switch from the current one to the next "own" one

In the previous version, everything seemed to be showing correctly.
Maybe the problem is related to the fact that the new version added links to the playing track? Maybe u can make some kind of stub for manually uploaded files.

**Screenshots**
Correct display:
![image](https://github.com/TheKing-OfTime/YandexMusicModClient/assets/74099154/dc95f276-c823-49ab-822d-46aef706d732)

Switching to a track uploaded manually:
![image](https://github.com/TheKing-OfTime/YandexMusicModClient/assets/74099154/bc24e99f-af08-4774-8d0c-eadb71f95d72)

**Comment by TheKing-OfTime** [comment]
Hello. Thanks for your report.
Are you sure that you are using the latest version of the modification? Looks like this issue may be related to the #1 issue.

**Comment by TheKing-OfTime** [comment]
Is "your" track published? Could you share a link to it?

**Comment by TheKing-OfTime** [comment]
> Maybe the problem is related to the fact that the new version added links to the playing track? Maybe u can make some kind of stub for manually uploaded files.
Modification checks if link is exists. So this shouldn't be the problem

**Comment by TheKing-OfTime** [comment]
I make some changes. Could you try install this patch manually and check if this fixes issue?
1. download file [app.zip](https://github.com/user-attachments/files/15905641/app.zip)
2. press Win + R
3. insert this `%localappdata%/Programs/YandexMusic/resources`
4. Unpack the zip archive in the folder with file replace.

**Comment by Shockwave211112** [comment]
> I make some changes. Could you try install this patch manually and check if this fixes issue?
> 
> 1. download file [app.zip](https://github.com/user-attachments/files/15905641/app.zip)
> 2. press Win + R
> 3. insert this `%localappdata%/Programs/YandexMusic/resources`
> 4. Unpack the zip archive in the folder with file replace.

Yes, now is shown correctly. 
gj

**Comment by Shockwave211112** [comment]
> Is "your" track published? Could you share a link to it?

No, the tracks are not published, of course) The links lead to 404. But now its works correctly.

**Comment by TheKing-OfTime** [comment]
> > I make some changes. Could you try install this patch manually and check if this fixes issue?
> > 
> > 1. download file [app.zip](https://github.com/user-attachments/files/15905641/app.zip)
> > 2. press Win + R
> > 3. insert this `%localappdata%/Programs/YandexMusic/resources`
> > 4. Unpack the zip archive in the folder with file replace.
> 
> Yes, now is shown correctly. 
> gj

Good. The thing I changed that cover image is optional now. 
I'll create a release with the fix and close this issue as complete tomorrow.
Thanks for your bug report.

**Comment by TheKing-OfTime** [comment]
Fix [released](https://github.com/TheKing-OfTime/YandexMusicModClient/releases/tag/onlyDiscordRPC)
