### ISSUE TITLE
After release YM beta 5.6.0 taskbar buttons not working

### ISSUE THREAD

**Issue by SergheyUmca** [TheKing-OfTime/YandexMusicModClient#4]
**Describe the bug**
After updating YM to 5.6.0, the buttons on the YM preview are pressed, but nothing happens.

**To Reproduce**
1. Launch the application.
2. Find the application icon on the taskbar.
3. Hover the cursor, a preview with control buttons will appear.
4. Press the control button, for example, play \ stop.
5. Nothing will happen.

**Expected behavior**
I expected that when I pressed the play control button, music would start playing, but the state of the player did not change.

**Screenshots/Video**
![image](https://github.com/TheKing-OfTime/YandexMusicModClient/assets/33039150/d99bf461-e2ca-47c3-8a15-4d941d9e0947)

**Client info (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Modification version 1.6.0
 - Yandex Music version 5.6.0

**Comment by TheKing-OfTime** [comment]
Thanks for your report. I can reproduce this bug. Bug identified and will be fixed in next release.

**Comment by TheKing-OfTime** [comment]
Fix released [1.6.1](https://github.com/TheKing-OfTime/YandexMusicModClient/releases/tag/onlyDiscordRPC)
