### ISSUE TITLE
Version YM 5.6.0, after hiding the application in the tray and restoring, the player control buttons are not displayed.

### ISSUE THREAD

**Issue by SergheyUmca** [TheKing-OfTime/YandexMusicModClient#5]
**Describe the bug**
Version YM 5.6.0, after hiding the application in the tray and restoring, when hovering over the application icon in the taskbar, the player control buttons are not displayed.

**To Reproduce**
1. Launch the application.
2. Click the cross in the upper right corner of the application window.
3. The application will collapse into the tray.
4. Expand the application by running it again (the expand button on the tray icon does not work, double-clicking on the tray icon does not work either).
5. Hover over the application icon on the taskbar.
6. There will be no player control buttons.

**Expected behavior**
The expectation is that after you have deployed the application from the tray, the player control buttons will appear on the taskbar when you hover the cursor over the application icon.

**Screenshots/Video**
![image](https://github.com/TheKing-OfTime/YandexMusicModClient/assets/33039150/92ec9677-c441-4fc2-8c3c-8609b49f9a2c)

**Client info (please complete the following information):**
 - OS: Windows 10 Pro 22h2
 - Modification version [e.g. 1.6.0]
 - Yandex Music version [e.g. 5.6.0]

**Comment by TheKing-OfTime** [comment]
Thanks for your report. I can reproduce this 2 bugs. They are identified and will be fixed in next release.

**Comment by TheKing-OfTime** [comment]
Fix released [1.6.1](https://github.com/TheKing-OfTime/YandexMusicModClient/releases/tag/onlyDiscordRPC)
