### ISSUE TITLE
Change Discord RPC status

### ISSUE THREAD

**Issue by Pupcheg** [TheKing-OfTime/YandexMusicModClient#6]
Change Discord RPC status to 'listening' instead of 'playing'

![image](https://github.com/user-attachments/assets/203a0597-0c31-4038-b04f-336b0fb9903c)

**Comment by TheKing-OfTime** [comment]
Hello. Thanks for your feature request.
Unfortunately Discord local RPC currently doesn't support listening type for activity. So i can't add it now. However as soon as Discord start support it, my modification switch to it automatically. You can see the check [here](https://github.com/TheKing-OfTime/YandexMusicModClient/blob/2bc97bb6c66e514132711f6b1f338c8e721a7962/src/main/lib/discordRichPresence.js#L50).

**Comment by TheKing-OfTime** [comment]
looks like they implemented this in canary 312559 (37ec590) Host 1.0.416 x64 (49895) Build Override: N/A Windows 11 64-bit (10.0.22631)
![image](https://github.com/user-attachments/assets/c9dc940f-52e1-4f4d-b9e0-8c8e754aca93)

**Comment by Pupcheg** [comment]
Also works in latest stable release
@TheKing-OfTime 
![image](https://github.com/user-attachments/assets/6adbb6ef-b302-4178-b702-e97994ba88af)
