### ISSUE TITLE
Discord RPC disappears on restart.

### ISSUE THREAD

**Issue by saberkovich** [TheKing-OfTime/YandexMusicModClient#7]
**Describe the bug**
When the music is on, if you close Discord, the Rich Presence disappears. You can return the Rich Presence only by restarting Yandex Music.

**To Reproduce**
1. Turn on the music to make Rich Presence appear.
2. Restart Discord.
3. See bug.

**Expected behavior**
It is necessary for the program to determine when the Discord program process opens or closes in order to avoid such cases.

**Client info (please complete the following information):**
 - OS: Windows 10 (Build 22H2)
 - Modification version: 1.8.4
 - Yandex Music version: 5.8.3

**Comment by TheKing-OfTime** [comment]
Thanks for your bug report. I can reproduce this. Apparently my previous fix to this problem doesn't work. Will be fixed in next release

**Comment by TheKing-OfTime** [comment]
Should be fixed in 1.9.0. Reopen if this bug will reappear
