### ISSUE TITLE
Incorrect display of podcasts in Discord RPC

### ISSUE THREAD

**Issue by saberkovich** [TheKing-OfTime/YandexMusicModClient#8]
**Describe the bug**
When you listen to a podcast, the Discord profile says "loading".

**To Reproduce**
1. Enable the podcast.
2. Look at the Discord profile.

**Expected behavior**
Make some kind of unique display for podcasts, or make them not visible in Discord RPC.

**Screenshots/Video**
![изображение](https://github.com/user-attachments/assets/51303e13-71df-4587-a8a8-bf83050706b1)

**Client info (please complete the following information):**
 - OS: Windows 10 (Build 22H2)
 - Modification version: 1.8.4
 - Yandex Music version: 5.8.3

**Comment by TheKing-OfTime** [comment]
Thanks for your bug report. I can reproduce this. Will be fixed in next release

**Comment by TheKing-OfTime** [comment]
Fixed in 1.9.0
