### ISSUE TITLE
Кнопка "слушать в Яндекс Музыке"

### ISSUE THREAD

**Issue by FreshLimon** [TheKing-OfTime/YandexMusicModClient#9]
Возможно ли добавить кнопку слушать в Яндекс музыке. Которая будет позволять открыть песню самому. По аналогии с Spotify RPC. В русской версии это либо слушать вместе, либо слушать в Spotify

![image](https://github.com/user-attachments/assets/bc6d4d6c-309f-466d-a7da-00de8c1ab18d)

**Comment by TheKing-OfTime** [comment]
Привет. Спасибо за предложение.
Кнопки уже добавлены. Однако в последних обновлениях Дискорд имеет баг в котором не видно кнопки у своего статуса.(Остальные пользователи видят кнопки в вашем профиле)
![image](https://github.com/user-attachments/assets/722428bf-f28e-49e2-a44d-b92cb19adb3e)

Я сообщил об этом баге сотруднику. Он сказал что скоро исправят.
![image](https://github.com/user-attachments/assets/afa13be0-1a76-4cbf-bd14-ab4d1b0306ee)

А вот кнопки "слушать вмесете" в обозримом будущем точно не будет. Так как в не костыльном исполнении это очень сложный функционал которым если кто то и займётся, то это будет сам Яндекс.
